apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: aws-west-1-warehouse-017
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: aws-west-1
connection:
  type: warehouse
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - aws-west-1-warehouse-017-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
