apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: azure-west-1-database-006
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: azure-west-1
connection:
  type: database
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - azure-west-1-database-006-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
