apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: azure-east-1-vector-store-003
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: azure-east-1
connection:
  type: vector-store
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
vectorIndex:
  name: azure-east-1-vector-store-003-index
  dims: 1536
  metric: cosine
auth:
  method: apikey
  secretRefs:
    - azure-east-1-vector-store-003-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
