apiVersion: tdf.7sg.ai/v1
kind: TargetDefinition
metadata:
  name: azure-global
  version: "1.0.0"
  tags:
    provider: azure
    geo: us
target:
  provider: azure
  regions:
    - eastus
    - eastus2
    - westus
    - westus2
    - westus3
    - centralus
    - northcentralus
    - southcentralus
    - westcentralus
    - canadacentral
    - canadaeast
    - brazilsouth
    - northeurope
    - westeurope
    - uksouth
    - ukwest
    - francecentral
    - germanywestcentral
    - norwayeast
    - switzerlandnorth
    - swedencentral
    - uaenorth
    - southafricanorth
    - eastasia
    - southeastasia
    - japaneast
    - japanwest
    - australiaeast
    - australiasoutheast
    - koreacentral
  services:
    - name: k8s
      type: kubernetes
    - name: store
      type: object-store
    - name: secret-mgr
      type: secrets
