apiVersion: tdf.7sg.ai/v1
kind: TargetDef
metadata:
  name: bad-017
  version: "1.0.0"
  tags:
    provider: azure
    geo: us
target:
  provider: azure
  regions:
    - eastus2
  services:
    - name: k8s
      type: kubernetes
    - name: store
      type: object-store
    - name: secret-mgr
      type: secrets
