apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: dsdf-12-4
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: target-12
connection:
  type: database
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - dsdf-12-4-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
