apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: dsdf-055
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: azure-east
connection:
  type: filesystem
  provider: provider-0
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - dsdf-055-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
