apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: dsdf-05-2
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: target-05
connection:
  type: filesystem
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - dsdf-05-2-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
