apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: dsdf-13-3
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: target-13
connection:
  type: api
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - dsdf-13-3-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
