apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: dsdf-039
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: azure-east
connection:
  type: queue
  provider: provider-4
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - dsdf-039-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
