apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: local-dev-vector-store-033
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: local-dev
connection:
  type: vector-store
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
vectorIndex:
  name: local-dev-vector-store-033-index
  dims: 1536
  metric: cosine
auth:
  method: apikey
  secretRefs:
    - local-dev-vector-store-033-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
