apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: local-dev-object-store-030
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: local-dev
connection:
  type: object-store
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - local-dev-object-store-030-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
