apiVersion: tdf.7sg.ai/v1
kind: TargetDefinition
metadata:
  name: onprem-target
  version: "1.0.0"
  tags:
    provider: onprem
    geo: us
target:
  provider: onprem
  regions:
    - local
  services:
    - name: k8s
      type: kubernetes
    - name: store
      type: object-store
    - name: secret-mgr
      type: secrets
    - name: fs
      type: file-store
