apiVersion: tdf.7sg.ai/v1
kind: TargetDefinition
metadata:
  name: target-13
  version: "1.0.0"
  tags:
    provider: aws
    geo: us
target:
  provider: aws
  regions:
    - us-west-2
  services:
    - name: k8s
      type: kubernetes
    - name: store
      type: object-store
    - name: secret-mgr
      type: secrets
