apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: taxi-data
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: azure-east
connection:
  type: warehouse
  provider: azure-synapse-spark
  endpoint: https://example-synapse.dev.azuresynapse.net
  resource: financial-analysis-pool
  format: delta
auth:
  method: azure-managed-identity
  secretRefs: []
secrets:
  provider: azureKeyVault
  inheritFromWdf: false
  secretRefs:
    - name: azure-synapse-workspace-name
      injectAs: env
      envVar: AZURE_SYNAPSE_WORKSPACE_NAME
      externalRef:
        provider: azure-keyvault
        key: azure-synapse-workspace-name
    - name: azure-synapse-spark-pool-name
      injectAs: env
      envVar: AZURE_SYNAPSE_SPARK_POOL_NAME
      externalRef:
        provider: azure-keyvault
        key: azure-synapse-spark-pool-name
