apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: taxi-data
  version: "1.0.0"
  tags:
    service: spark
    purpose: curated-dataset
    env: prod
home:
  tdfRef: TODO
connection:
  type: warehouse
  provider: azure-synapse-spark
  endpoint: https://sherpa-synapse-ws.dev.azuresynapse.net
  resource: financial-analysis-pool
  format: delta
auth:
  method: azure-managed-identity
  secretRefs: []
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
