apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: deep-api
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: azure-east
connection:
  type: api
  provider: openai-compatible
  endpoint: https://example.com
  resource: example-resource
auth:
  method: apikey
  secretRefs:
    - deep-api-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
